openapi: 3.0.0
info:
  title: Main
  description: >-
    # Servers and Resources


    LP (Licensing Platform) -
    [https://music.clicknclear.com](https://music.clicknclear.com)  

    LVS (License Verification System) -
    [https://verification.clicknclear.com](https://verification.clicknclear.com)  

    Support Email -
    [support@clicknclear.com](https://mailto:support@clicknclear.com)  

    Tech Team Email -
    [techteam@clicknclear.com](https://mailto:techteam@clicknclear.com)


    # API Keys


    To create an API key please make sure you first contact a ClicknClear admin
    so they can enable API Key support for your user account.


    ## Api Key Setup


    - Navigate to
    [https://music.clicknclear.com/profile](https://music.clicknclear.com/profile)
    (login if you are not)
        
    - If your account is setup correctly you should have an "API Keys" section.
    If you cannot see this section please get in contact via the support email
    or the Tech Team email.
        
    - Click on the "Create API Key" button
        
    - Enter a name for the API Key, this is to help you identify it at a later
    date
        
    - Copy the API Key ID and the API Key Secret and store them somewhere safe,
    you will not be able to view the Key Secret again.
        
    - To use the postman collection, copy the API Key ID and the API Key Secret
    into the relevant postman environment variables.
        

    # Authentication


    See the Login routes for more information on how to get Access Tokens and
    Refresh Tokens.  

    There is a Postman script on the Login route that will automatically add the
    access and refresh tokens to your postman environment.  

    To authenticate your requests to the ClicknClear API add the access token to
    the "Authorization" header with the value of "Bearer {ACCESS_TOKEN}".


    EG:


    ```

    'Authorization': 'Bearer XXXXX'

     ```

    # Server Responses


    Throughout our APIs we heavily utilise [HTTP
    Codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) to signify
    the status of the request. In general, a 4xx status code will have the error
    type and usually a message to help the developer know why the request
    failed. Below is an example of an erroneous login request.


    ```

    {
        "statusCode": 400,
        "error": "Bad Request",
        "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"apiKey\"\n    ],\n    \"message\": \"Required\"\n  }\n]"
    }

     ```

    If you are consistently receiving 400s or even 500s and you're not sure how
    to fix it please email the Tech Team email with steps to reproduce your
    issue.
  version: 1.0.0
servers:
  - url: https://music.clicknclear.com
    description: Used for authentication
  - url: https://verification.clicknclear.com
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: A collection of requests that involve authentication
  - name: Organisations
  - name: Seasons V1
    description: >-
      This folder contains all requests for the LVS Seasons and related
      entities.


      Seasons can be viewed and edited through:
      [https://verification.clicknclear.com/en-gb/my-seasons.](https://verification.clicknclear.com/en-gb/my-seasons.)  

      When testing feel free to create a sandbox or test season.  

      If you wanted to test the season signup and responses you can do so by
      going through the season signup URL. We recommend signing up to the season
      with a different user account to the one which can create seasons. This
      will ensure that the what you see will reflect what the Team/Athletes see


      EG: Producer Account:
      [tristan@clicknclear.com](https://mailto:tristan@clicknclear.com) Signup
      Account:
      [tristan+test@clicknclear.com](https://mailto:tristan+test@clicknclear.com)
  - name: Verification Job V1
    description: >-
      This folder contains all of the requests for verification jobs and their
      related entities
paths:
  /api/auth/api-key/login:
    post:
      tags:
        - Auth
      summary: Login
      description: >-
        This endpoint should be used to get an access token and a refresh token
        from a key & secret. Once the access token is fetched it should be used
        to authenticate to other API endpoints.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                key: '{{keyID}}'
                secret: '{{keySecret}}'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/access-token/refresh:
    post:
      tags:
        - Auth
      summary: Refresh
      description: >-
        This endpoint can be used to get a new access token from a refresh token
        without having to call the login API endpoint again.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refreshToken: '{{refreshToken}}'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/orgs/me:
    get:
      tags:
        - Organisations
      summary: Get My Organisations
      description: >-
        This endpoint can be used to get all organisations that this user
        account has access to.
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 12 Jul 2024 13:02:19 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Server:
              schema:
                type: string
                example: nginx
            vary:
              schema:
                type: string
                example: Origin
            x-ratelimit-limit:
              schema:
                type: integer
                example: '1000'
            x-ratelimit-remaining:
              schema:
                type: integer
                example: '999'
            x-ratelimit-reset:
              schema:
                type: integer
                example: '60'
            tdm-reservation:
              schema:
                type: integer
                example: '1'
            x-robots-tag:
              schema:
                type: string
                example: noai, noimageai
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Strict-Transport-Security:
              schema:
                type: string
                example: ': max-age=63072000; includeSubDomains; preload'
            Content-Encoding:
              schema:
                type: string
                example: gzip
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1
                  name: ClicknClear
                  logo:
                    id: 7
                    fileType: Image
                    fileName: black logo+.jpg
                    signedUrl: https://example.clicknclear.com
                  createdAt: '2022-01-14T16:06:50.234Z'
                  deletedAt: null
                  parentId: null
                  updatedAt: '2023-03-01T13:02:59.000Z'
                  isEventProducer: true
                - id: 8
                  name: ClicknClear School
                  createdAt: '2022-10-04T16:38:39.642Z'
                  deletedAt: null
                  parentId: 1
                  updatedAt: '2022-10-04T16:38:39.642Z'
                  isEventProducer: true
                - id: 13
                  name: Compete
                  createdAt: '2023-02-16T09:48:14.492Z'
                  deletedAt: null
                  parentId: 8
                  updatedAt: '2023-02-16T09:48:14.492Z'
                  isEventProducer: true
                - id: 14
                  name: Your Organization
                  createdAt: '2023-03-02T19:43:59.535Z'
                  deletedAt: null
                  parentId: 1
                  updatedAt: '2023-03-02T19:43:59.535Z'
                  isEventProducer: true
                - id: 15
                  name: Example Organization
                  logo:
                    id: 26
                    fileType: Image
                    fileName: YOUR PARENT ORGANIZATION LOGO.png
                    signedUrl: https://example.clicknclear.com
                  createdAt: '2024-02-22T20:47:20.025Z'
                  deletedAt: null
                  parentId: 1
                  updatedAt: '2024-02-27T14:39:52.000Z'
                  isEventProducer: true
                - id: 16
                  name: HERmesa
                  logo:
                    id: 27
                    fileType: Image
                    fileName: Screenshot 2024-02-27 at 15.53.47.png
                    signedUrl: https://example.clicknclear.com
                  createdAt: '2024-02-27T20:53:53.002Z'
                  deletedAt: null
                  parentId: 1
                  updatedAt: '2024-02-27T20:53:53.002Z'
                  isEventProducer: true
                - id: 17
                  name: Example Organization
                  logo:
                    id: 32
                    fileType: Image
                    fileName: LVS Guide graphics.png
                    signedUrl: https://example.clicknclear.com
                  createdAt: '2024-02-28T13:38:33.671Z'
                  deletedAt: null
                  parentId: 15
                  updatedAt: '2024-03-01T19:04:10.000Z'
                  isEventProducer: true
                - id: 18
                  name: Your Child Org 1
                  logo:
                    id: 31
                    fileType: Image
                    fileName: CHILD ORG LOGO.png
                    signedUrl: https://example.clicknclear.com
                  createdAt: '2024-02-28T20:02:03.127Z'
                  deletedAt: null
                  parentId: 17
                  updatedAt: '2024-02-28T20:02:03.127Z'
                  isEventProducer: true
  /api/public/v1/season:
    get:
      tags:
        - Seasons V1
      summary: Get Seasons
      description: >-
        The get seasons endpoint returns all seasons that the current user
        account has access to. This includes any seasons of child
        organisations.  

        To view the annotated Typescript response please go to:
        [https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/season.ts](https://github.com/ClicknClear/Public-Resources/blob/d8a84505e9ee08c826839bac462a36a79e5cf0f9/packages/lvs-types/src/v1/season.ts)
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 12 Jul 2024 13:04:46 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '4996'
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 14
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: Everything Enabled Season
                  endDate: '2024-06-27T00:00:00.000Z'
                  startDate: '2024-06-20T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields: []
                - id: 11
                  isLocked: false
                  territories: []
                  organisationId: 17
                  title: Your Season Title
                  endDate: '2025-02-20T00:00:00.000Z'
                  startDate: '2024-03-10T00:00:00.000Z'
                  signupFields:
                    - id: 50
                      isRequired: true
                      options: []
                      order: 0
                      question: Please enter your participant ID
                      description: ''
                      type: shortAnswer
                      key: null
                - id: 10
                  isLocked: false
                  territories: []
                  organisationId: 15
                  title: Example Season
                  endDate: '2025-01-31T00:00:00.000Z'
                  startDate: '2024-02-22T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields:
                    - id: 69
                      isRequired: true
                      options: []
                      order: 0
                      question: What's your favourite colour?
                      description: ''
                      type: shortAnswer
                      key: null
                - id: 8
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: Jack Regression Test Season
                  endDate: '2024-07-11T00:00:00.000Z'
                  startDate: '2023-12-31T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields:
                    - id: 44
                      isRequired: true
                      options: []
                      order: 0
                      question: Question 1
                      description: ''
                      type: shortAnswer
                      key: null
                    - id: 45
                      isRequired: true
                      options: []
                      order: 1
                      question: Question 2
                      description: ''
                      type: shortAnswer
                      key: null
                    - id: 46
                      isRequired: true
                      options: []
                      order: 2
                      question: Question 3
                      description: ''
                      type: shortAnswer
                      key: null
                - id: 7
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: testing edits
                  endDate: '2024-02-28T00:00:00.000Z'
                  startDate: '2024-01-31T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields:
                    - id: 40
                      isRequired: true
                      options: []
                      order: 0
                      question: s1
                      description: ''
                      type: shortAnswer
                      key: null
                    - id: 41
                      isRequired: true
                      options: []
                      order: 1
                      question: s2
                      description: ''
                      type: shortAnswer
                      key: null
                - id: 6
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: Work Season
                  endDate: '2024-01-25T00:00:00.000Z'
                  startDate: '2024-01-18T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields: []
                - id: 5
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: New Season
                  endDate: '2024-01-15T00:00:00.000Z'
                  startDate: '2024-01-08T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields: []
                - id: 4
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: robins season
                  endDate: '2024-01-10T00:00:00.000Z'
                  startDate: '2024-01-03T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields: []
                - id: 3
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: SR Season 2023 / 2025
                  endDate: '2024-02-29T00:00:00.000Z'
                  startDate: '2023-03-01T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields:
                    - id: 34
                      isRequired: true
                      options: []
                      order: 0
                      question: edited q
                      description: ''
                      type: shortAnswer
                      key: null
                    - id: 35
                      isRequired: true
                      options: []
                      order: 1
                      question: fewfewfwe
                      description: ''
                      type: shortAnswer
                      key: null
                - id: 1
                  isLocked: false
                  territories: []
                  organisationId: 1
                  title: KANSAS 2023/2024
                  endDate: '2023-10-31T00:00:00.000Z'
                  startDate: '2023-01-01T00:00:00.000Z'
                  inviteURL: https://example.clicknclear.com
                  signupFields: []
  /api/public/v1/season/{seasonId}/entries:
    post:
      tags:
        - Seasons V1
      summary: Get Entries
      description: >-
        The Get Entries API endpoint can be used to get season entries along
        with any license data.


        The shape of the result body can be found starting in:
        [https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/entry.ts](https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/entry.ts)  

        with the IEntryV1 type. Due to the complex return type the exact types
        are spread amongst a few different files.


        This endpoint has an optional request body which can be used to filter
        down the results. If no body is supplied it will return all results. By
        supplying the body, you can filter based on the updatedAfter or by the
        signup field responses. The zod schemas can be found in this file:
        [https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/entry.ts](https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/entry.ts)
        and it is called getEntriesQuerySchemaV1.


        Example requests can be found filtering by both updatedAfter and signup
        fields.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      parameters:
        - name: seasonId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            content-type:
              schema:
                type: string
                example: application/json; charset=utf-8
            content-length:
              schema:
                type: integer
                example: '8936'
            date:
              schema:
                type: string
                example: Fri, 12 Jul 2024 10:11:28 GMT
            connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: All Entries
                  value:
                    - id: 27
                      email: tristan+test@clicknclear.com
                      name: My Test User
                      fields:
                        - value: '123456789'
                          signupFieldId: 89
                          key: externalId
                      soundRecording:
                        createdAt: '2024-07-11T15:21:26.706Z'
                        downloadURL: https://example.clicknclear.com
                        uploadFileName: Eric Clapton - Lay Down Sally (Live).mp3
                        licenseStatus: Unverified
                        songsConfirmedAt: '2024-07-11T16:22:56.000Z'
                        updatedAt: '2024-07-11T15:22:56.000Z'
                        status: Complete
                        songs:
                          - title: Lay Down Sally (Live)
                            artists: Eric Clapton
                            endTime: 310
                            startTime: 0
                            cncMixId: null
                            cncId: 5fb5a20bc52b507e3f154ae1
                            composer: null
                            isrc: NLRD51424699
                            iswc: null
                            publisher: null
                            recordLabel: Black Barn Music
                            tunecode: null
                            yearOfRelease: 2020
                            upc: null
                            manualStatus: null
                            licenseStatus: Unverified
                            licenseChecks:
                              Licensee Name Match: Unknown
                              License Source Matches: Unknown
                              Title Matches: Unknown
                              Artists Match: Unknown
                              Master Choreography Rights: Unknown
                              Master Adaptation Rights: Unknown
                              Master Duplication Rights: Unknown
                              Publishing Choreography Rights: Unknown
                              Publishing Adaptation Rights: Unknown
                              Publishing Duplication Rights: Unknown
                              Valid Date: Unknown
                              Full Ownership: Unknown
                              Territory Match:
                                GB: Unknown
                                AF: Unknown
                                US: Unknown
                            licenseData:
                              bespokeAgreement: null
                              licenseSource: Pending License
                              cncLicense: null
                              externalLicense: null
                              publicDomainProof: null
                    - id: 28
                      email: tristan+test@clicknclear.com
                      name: No Signup User
                      fields:
                        - value: '123456789'
                          signupFieldId: 89
                          key: externalId
                      soundRecording: null
                    - id: 26
                      email: tristan+test@clicknclear.com
                      name: Partial Territories
                      fields: []
                      soundRecording:
                        createdAt: '2024-07-08T07:20:14.938Z'
                        downloadURL: https://example.clicknclear.com
                        uploadFileName: MY_MIX_WITH_MATCHES.mp3
                        licenseStatus: Licensed
                        songsConfirmedAt: '2024-07-08T08:25:18.000Z'
                        updatedAt: '2024-07-08T07:25:18.000Z'
                        status: Complete
                        songs:
                          - title: She's My Addiction
                            artists: Fozzy
                            endTime: 136
                            startTime: 0
                            cncMixId: null
                            cncId: 5f4d360c6fce45507b4b3870
                            composer: null
                            isrc: null
                            iswc: null
                            publisher: null
                            recordLabel: Century Media
                            tunecode: null
                            yearOfRelease: 2012
                            upc: null
                            manualStatus: null
                            licenseStatus: Licensed
                            licenseChecks:
                              Licensee Name Match: Accepted
                              License Source Matches: Accepted
                              Title Matches: Accepted
                              Artists Match: Accepted
                              Master Choreography Rights: Accepted
                              Master Adaptation Rights: Accepted
                              Master Duplication Rights: Accepted
                              Publishing Choreography Rights: Accepted
                              Publishing Adaptation Rights: Accepted
                              Publishing Duplication Rights: Accepted
                              Valid Date: Accepted
                              Full Ownership: Accepted
                              Territory Match:
                                GB: Rejected
                                AF: Accepted
                                US: Rejected
                            licenseData:
                              bespokeAgreement: null
                              licenseSource: ClicknClear
                              cncLicense:
                                ref: cff52747f638da48490f7b8b6e370620
                                datePurchased: '2024-07-08T08:19:41.000Z'
                                validTo: '2025-07-08T08:19:41.000Z'
                                downloadURL: https://example.clicknclear.com
                                rights:
                                  - name: Standard
                                    variant: 1 Year
                                territories:
                                  - AF
                              externalLicense: null
                              publicDomainProof: null
                          - title: All Black
                            artists: Good Charlotte
                            endTime: 10
                            startTime: 0
                            cncMixId: null
                            cncId: 5f416a3771aa9d16b0886b07
                            composer: null
                            isrc: USSM10607451
                            iswc: null
                            publisher: null
                            recordLabel: Epic/Daylight
                            tunecode: null
                            yearOfRelease: 2007
                            upc: null
                            manualStatus: null
                            licenseStatus: Licensed
                            licenseChecks:
                              Licensee Name Match: Accepted
                              License Source Matches: Accepted
                              Title Matches: Accepted
                              Artists Match: Accepted
                              Master Choreography Rights: Accepted
                              Master Adaptation Rights: Accepted
                              Master Duplication Rights: Accepted
                              Publishing Choreography Rights: Accepted
                              Publishing Adaptation Rights: Accepted
                              Publishing Duplication Rights: Accepted
                              Valid Date: Accepted
                              Full Ownership: Accepted
                              Territory Match:
                                GB: Rejected
                                AF: Accepted
                                US: Rejected
                            licenseData:
                              bespokeAgreement: null
                              licenseSource: ClicknClear
                              cncLicense:
                                ref: cff52747f638da48490f7b8b6e370620
                                datePurchased: '2024-07-08T08:19:41.000Z'
                                validTo: '2025-07-08T08:19:41.000Z'
                                downloadURL: https://example.clicknclear.com
                                rights:
                                  - name: Standard
                                    variant: 1 Year
                                territories:
                                  - AF
                              externalLicense: null
                              publicDomainProof: null
                    - id: 25
                      email: tristan+test@clicknclear.com
                      name: Tristan
                      fields: []
                      soundRecording:
                        createdAt: '2024-07-05T09:18:42.566Z'
                        downloadURL: https://example.clicknclear.com
                        uploadFileName: John Williams - Main Theme (From _Jurassic Park_).mp3
                        licenseStatus: Licensed
                        songsConfirmedAt: '2024-07-05T10:22:00.000Z'
                        updatedAt: '2024-07-05T09:22:00.000Z'
                        status: Complete
                        songs:
                          - title: Main Theme (From "Jurassic Park")
                            artists: John Williams
                            endTime: 330
                            startTime: 0
                            cncMixId: null
                            cncId: 5f3d053b47113550ed1a80e9
                            composer: null
                            isrc: USSM19504354
                            iswc: null
                            publisher: null
                            recordLabel: null
                            tunecode: null
                            yearOfRelease: null
                            upc: '0886447845035'
                            manualStatus: null
                            licenseStatus: Licensed
                            licenseChecks:
                              Licensee Name Match: Accepted
                              License Source Matches: Accepted
                              Title Matches: Accepted
                              Artists Match: Accepted
                              Master Choreography Rights: Accepted
                              Master Adaptation Rights: Accepted
                              Master Duplication Rights: Accepted
                              Publishing Choreography Rights: Accepted
                              Publishing Adaptation Rights: Accepted
                              Publishing Duplication Rights: Accepted
                              Valid Date: Accepted
                              Full Ownership: Accepted
                              Territory Match:
                                GB: Accepted
                                AF: Accepted
                                US: Accepted
                            licenseData:
                              bespokeAgreement: null
                              licenseSource: ClicknClear
                              cncLicense:
                                ref: 42ae53188f3112058776f1b58610b9ac
                                datePurchased: '2024-07-05T12:40:57.000Z'
                                validTo: '2025-07-05T10:18:10.000Z'
                                downloadURL: https://example.clicknclear.com
                                rights:
                                  - name: Standard
                                    variant: 1 Year
                                territories:
                                  - AD
                                  - AE
                                  - AF
                                  - AG
                                  - AL
                                  - AM
                                  - AO
                                  - AR
                                  - AT
                                  - AU
                                  - AZ
                                  - BA
                                  - BB
                                  - BD
                                  - BE
                                  - BF
                                  - BG
                                  - BH
                                  - BI
                                  - BJ
                                  - BN
                                  - BO
                                  - BR
                                  - BS
                                  - BT
                                  - BW
                                  - BY
                                  - BZ
                                  - CA
                                  - CF
                                  - CG
                                  - CI
                                  - CL
                                  - CM
                                  - CN
                                  - CO
                                  - CR
                                  - CU
                                  - CV
                                  - CY
                                  - CZ
                                  - DJ
                                  - DK
                                  - DM
                                  - DO
                                  - DZ
                                  - EC
                                  - EE
                                  - EG
                                  - EH
                                  - ER
                                  - ES
                                  - ET
                                  - FI
                                  - FJ
                                  - FR
                                  - GA
                                  - GB
                                  - GD
                                  - GE
                                  - GM
                                  - GN
                                  - GQ
                                  - GR
                                  - GT
                                  - GW
                                  - GY
                                  - HK
                                  - HN
                                  - HR
                                  - HT
                                  - HU
                                  - ID
                                  - IE
                                  - IL
                                  - IN
                                  - IQ
                                  - IR
                                  - IS
                                  - IT
                                  - JM
                                  - JO
                                  - KE
                                  - KG
                                  - KH
                                  - KM
                                  - KN
                                  - KR
                                  - KW
                                  - KZ
                                  - LA
                                  - LB
                                  - LC
                                  - LK
                                  - LR
                                  - LS
                                  - LT
                                  - LU
                                  - LV
                                  - LY
                                  - MA
                                  - MC
                                  - MD
                                  - ME
                                  - MG
                                  - MK
                                  - ML
                                  - MN
                                  - MR
                                  - MT
                                  - MU
                                  - MV
                                  - MW
                                  - MX
                                  - MY
                                  - MZ
                                  - NA
                                  - NC
                                  - NE
                                  - NG
                                  - NI
                                  - NL
                                  - 'NO'
                                  - NP
                                  - NR
                                  - NZ
                                  - OM
                                  - PA
                                  - PE
                                  - PF
                                  - PG
                                  - PH
                                  - PK
                                  - PL
                                  - PR
                                  - PT
                                  - PY
                                  - QA
                                  - RO
                                  - RS
                                  - RU
                                  - RW
                                  - SA
                                  - SB
                                  - SC
                                  - SE
                                  - SG
                                  - SI
                                  - SK
                                  - SL
                                  - SM
                                  - SN
                                  - SO
                                  - SR
                                  - SS
                                  - ST
                                  - SV
                                  - SY
                                  - SZ
                                  - TD
                                  - TG
                                  - TH
                                  - TJ
                                  - TM
                                  - TN
                                  - TR
                                  - TT
                                  - TW
                                  - TZ
                                  - UA
                                  - UG
                                  - US
                                  - UY
                                  - UZ
                                  - VA
                                  - VC
                                  - VE
                                  - VN
                                  - VU
                                  - WS
                                  - YE
                                  - ZA
                                  - ZM
                                  - ZW
                              externalLicense: null
                              publicDomainProof: null
                example-1:
                  summary: Filter By Signup Field
                  value: {}
            text/plain:
              schema:
                type: string
              example: ''
  /api/public/v1/verification-job:
    post:
      tags:
        - Verification Job V1
      summary: Create Verification Job
      description: >-
        # Create Verification Job


        The create verification job endpoint can match and verify audio or video
        files against the provided licensing information and any ClicknClear
        licenses.  

        ClicknClear licenses will be fetched automatically based on the provided
        email address.


        Any songs found in the audio file will be matched against the license
        files provided.  

        The verification job process is asynchronous, on creation, you will
        receive the job with an ID, you can use this to poll the Get
        Verification Job Endpoint or you can set a webhook (preferred) for the
        'Verification Job - Status Update' event, this event is fired when the
        job finishes processing. To setup a webhook please see the online
        documentation:
        [https://github.com/ClicknClear/Public-Resources/blob/main/docs/verification/Verification.md#webhooks](https://github.com/ClicknClear/Public-Resources/blob/main/docs/verification/Verification.md#webhooks)


        The 'Verification Job - Status Update' webhook event is invoked with a
        minimal payload, the full verification job can then be fetched using the
        Get Verification Job endpoint. See 'IVerificationJobStatusUpdateV1' for
        the payload type.


        For details on return types and the request payload please see the
        annotated typescript types:
        [https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/verificationJob.ts](https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/verificationJob.ts)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Tristan Barlow
                email: tristan@clicknclear.com
                requiredTerritories:
                  - US
                  - GB
                startDate: '2024-09-01'
                endDate: '2024-09-04'
                externalId: '1234567890'
                organisationId: 1
                audioFileURL: >-
                  https://clicknclear-public-resources.s3.eu-west-1.amazonaws.com/lvs/TEST_MIX.mp3
                tags:
                  - September Event 2024
                  - '2024'
                  - Seniors
                licenseDetails:
                  - licenseSource: Other
                    licenseSourceName: Other Platform
                    licenseFileURLs:
                      - >-
                        https://clicknclear-public-resources.s3.eu-west-1.amazonaws.com/lvs/TEST_LICENSE.pdf
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            content-type:
              schema:
                type: string
                example: application/json; charset=utf-8
            content-length:
              schema:
                type: integer
                example: '348'
            date:
              schema:
                type: string
                example: Mon, 16 Sep 2024 16:45:08 GMT
            connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                id: 4
                name: Tristan Barlow
                email: tristan@clicknclear.com
                requiredTerritories:
                  - US
                  - GB
                externalId: '1234567890'
                organisationId: 1
                soundRecordingId: null
                errorMessage: ''
                status: Created
                endDate: '2024-09-04T00:00:00.000Z'
                startDate: '2024-09-01T00:00:00.000Z'
                tags:
                  - September Event 2024
                  - '2024'
                  - Seniors
                recording: null
  /api/public/v1/verification-job/{verificationJobId}:
    get:
      tags:
        - Verification Job V1
      summary: Get Verification Job
      description: >-
        The get verification job endpoint can be used to get a single
        verification job from its ID.


        The verification job is returned in full including any and all licensing
        data.


        To view the response type please see:
        [https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/verificationJob.ts](https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/verificationJob.ts).
      parameters:
        - name: verificationJobId
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            content-type:
              schema:
                type: string
                example: application/json; charset=utf-8
            content-length:
              schema:
                type: integer
                example: '2485'
            date:
              schema:
                type: string
                example: Tue, 17 Sep 2024 07:31:45 GMT
            connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                id: 4
                name: Tristan Barlow
                email: tristan@clicknclear.com
                requiredTerritories:
                  - US
                  - GB
                externalId: '1234567890'
                organisationId: 1
                soundRecordingId: 133
                errorMessage: ''
                status: Completed
                endDate: '2024-09-04T00:00:00.000Z'
                startDate: '2024-09-01T00:00:00.000Z'
                tags:
                  - September Event 2024
                  - '2024'
                  - Seniors
                recording:
                  createdAt: '2024-09-16T16:45:09.298Z'
                  downloadURL: >-
                    https://cnc-sound-recordings-staging.s3.eu-west-1.amazonaws.com/9fe09e66082651af69024a566a7fd0b9.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIATK64JFLFLBA4EBGI%2F20240917%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20240917T073145Z&X-Amz-Expires=216000&X-Amz-Signature=4fe92aaa9729555b583cc527c2dca012a88fbe003286de24facf89aabac587d6&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%20%3D%22verification-jobs%2F845dae593a60280092554d2e125b3db7.mp3%22&response-content-type=audio%2Fmpeg&x-id=GetObject
                  uploadFileName: verification-jobs/845dae593a60280092554d2e125b3db7.mp3
                  licenseStatus: Unverified
                  songsConfirmedAt: null
                  updatedAt: '2024-09-16T16:45:17.000Z'
                  status: Complete
                  songs:
                    - title: Start a Fire
                      artists: Who's Molly?
                      endTime: 20
                      startTime: 0
                      cncMixId: null
                      cncId: 5f0470bfb11d420440942a35
                      composer: null
                      isrc: GB89R1600173
                      iswc: null
                      publisher: null
                      recordLabel: null
                      tunecode: null
                      yearOfRelease: null
                      upc: '5054526103603'
                      manualStatus: null
                      licenseStatus: Unverified
                      licenseChecks:
                        Publishing Adaptation Rights: Unknown
                        Publishing Duplication Rights: Unknown
                        Publishing Choreography Rights: Unknown
                        Title Matches: Unknown
                        Artists Match: Unknown
                        Full Ownership: Unknown
                        Valid Date: Unknown
                        License Source Matches: Unknown
                        Licensee Name Match: Rejected
                        Territory Match:
                          US: Unknown
                          GB: Unknown
                      licenseData:
                        bespokeAgreement: null
                        licenseSource: Other
                        cncLicense: null
                        externalLicense:
                          id: 133
                          sourceName: Other Platform
                          files:
                            - id: 104
                              downloadURL: >-
                                http://lvs.local.clicknclear.com:3001/api/files/download?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXQiOiJjbGlja25jbGVhci12ZXJpZmljYXRpb24tbGljZW5zZXMtc3RhZ2luZyIsImtleSI6ImV4dGVybmFsLWxpY2Vuc2VzL2MxOTg2MjBlZGYyMmI5YzM3ZDRiNjliNjMyOWY1NDNlLnBkZiIsImZpbGVuYW1lIjoiVW5rbm93bi5wZGYiLCJjb250ZW50VHlwZSI6ImFwcGxpY2F0aW9uL3BkZiIsImlhdCI6MTcyNjU1ODMwNSwiZXhwIjoxNzI2NjQ0NzA1fQ.sJXEJbXqDSXXZheAxRKSts9WaywT3A-VlT5HlEO9aVY
                        publicDomainProof: null
  /api/public/v1/verification-job/search:
    post:
      tags:
        - Verification Job V1
      summary: Search Verification Jobs
      description: >-
        # Search Verification Jobs by Tag


        The Search Verification Job by Tag endpoint allows you to retrieve a
        paginated list of verification jobs your organisation has submitted,
        filtered by tags.


        The endpoint will return verification jobs that match ANY tag provided
        in the query.


        It searches the Tags that were added to the Verification Job at the time
        of creation (via the Create Verification Job endpoint), returning a
        paginated list as well as a count of the total number of matched job
        records.


        The search endpoint will also accept an array of Job Statuses to further
        narrow the results to return only Verification Jobs with the requested
        status(s).


        Pagination is achieved with 'limit' and 'offset'. If omitted they will
        default to 25 and 0 respectively. The endpoint returns an array of
        Verification Jobs as well as the total count of all matches. Please
        consider that if you have many matching Verification Jobs, you may only
        receive the first page of results (eg 25) while the count of all
        matching results may be much higher. This allows you to effectively
        paginate.


        For details on return type (VerificationJobTagSearchResultsV1) and the
        request payload (VerificationJobTagSearchV1) please see the annotated
        typescript types:
        [https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/verificationJob.ts](https://github.com/ClicknClear/Public-Resources/blob/main/packages/lvs-types/src/v1/verificationJob.ts)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tags:
                  - '2024'
                  - Seniors
                statuses:
                  - Completed
                  - Created
                limit: 2
                offset: 2
      responses:
        '200':
          description: OK
          headers:
            content-type:
              schema:
                type: string
                example: application/json; charset=utf-8
            content-length:
              schema:
                type: integer
                example: '3690'
            Date:
              schema:
                type: string
                example: Wed, 09 Oct 2024 14:58:03 GMT
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                jobs:
                  - id: 3
                    name: Tristan Barlow
                    email: tristan@clicknclear.com
                    requiredTerritories:
                      - US
                      - GB
                    externalId: '1234567890'
                    organisationId: 1
                    soundRecordingId: 145
                    errorMessage: ''
                    status: Completed
                    endDate: '2024-09-04T00:00:00.000Z'
                    startDate: '2024-09-01T00:00:00.000Z'
                    tags:
                      - September Event 2024
                      - '2024'
                      - Seniors
                    recording:
                      createdAt: '2024-09-17T13:55:09.296Z'
                      downloadURL: >-
                        https://cnc-sound-recordings-staging.s3.eu-west-1.amazonaws.com/9fe09e66082651af69024a566a7fd0b9.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIATK64JFLFHXMJQUWO%2F20241009%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20241009T145803Z&X-Amz-Expires=216000&X-Amz-Signature=591806e89f85ba6a7093f124ddfd55fd7c54497bd506eb35e0f8dea8f7885a13&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%20%3D%22verification-jobs%2F845dae593a60280092554d2e125b3db7.mp3%22&response-content-type=audio%2Fmpeg&x-id=GetObject
                      uploadFileName: verification-jobs/845dae593a60280092554d2e125b3db7.mp3
                      licenseStatus: Unverified
                      songsConfirmedAt: null
                      updatedAt: '2024-09-17T13:55:09.000Z'
                      status: Failed
                      songs: []
                  - id: 4
                    name: Tristan Barlow
                    email: tristan@clicknclear.com
                    requiredTerritories:
                      - US
                      - GB
                    externalId: '1234567890'
                    organisationId: 1
                    soundRecordingId: 146
                    errorMessage: ''
                    status: Completed
                    endDate: '2024-09-04T00:00:00.000Z'
                    startDate: '2024-09-01T00:00:00.000Z'
                    tags:
                      - September Event 2024
                      - '2024'
                      - Seniors
                      - Test
                    recording:
                      createdAt: '2024-09-17T16:20:15.049Z'
                      downloadURL: >-
                        https://cnc-sound-recordings-staging.s3.eu-west-1.amazonaws.com/9fe09e66082651af69024a566a7fd0b9.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIATK64JFLFHXMJQUWO%2F20241009%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20241009T145803Z&X-Amz-Expires=216000&X-Amz-Signature=591806e89f85ba6a7093f124ddfd55fd7c54497bd506eb35e0f8dea8f7885a13&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%20%3D%22verification-jobs%2F845dae593a60280092554d2e125b3db7.mp3%22&response-content-type=audio%2Fmpeg&x-id=GetObject
                      uploadFileName: verification-jobs/845dae593a60280092554d2e125b3db7.mp3
                      licenseStatus: Unverified
                      songsConfirmedAt: null
                      updatedAt: '2024-09-17T16:20:22.000Z'
                      status: Complete
                      songs:
                        - title: Start a Fire
                          artists: Who's Molly?
                          endTime: 20
                          startTime: 0
                          cncMixId: null
                          cncId: 5f0470bfb11d420440942a35
                          composer: null
                          isrc: GB89R1600173
                          iswc: null
                          publisher: null
                          recordLabel: null
                          tunecode: null
                          yearOfRelease: null
                          upc: '5054526103603'
                          manualStatus: null
                          licenseStatus: Unverified
                          licenseChecks:
                            Publishing Adaptation Rights: Unknown
                            Publishing Duplication Rights: Unknown
                            Publishing Choreography Rights: Unknown
                            Title Matches: Unknown
                            Artists Match: Unknown
                            Full Ownership: Unknown
                            Valid Date: Unknown
                            License Source Matches: Unknown
                            Licensee Name Match: Rejected
                            Territory Match:
                              US: Unknown
                              GB: Unknown
                          licenseData:
                            bespokeAgreement: null
                            licenseSource: Other
                            cncLicense: null
                            externalLicense:
                              id: 134
                              sourceName: Other Platform
                              files:
                                - id: 106
                                  downloadURL: >-
                                    http://lvs.local.clicknclear.com:3001/api/files/download?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXQiOiJjbGlja25jbGVhci12ZXJpZmljYXRpb24tbGljZW5zZXMtc3RhZ2luZyIsImtleSI6ImV4dGVybmFsLWxpY2Vuc2VzL2MxOTg2MjBlZGYyMmI5YzM3ZDRiNjliNjMyOWY1NDNlLnBkZiIsImZpbGVuYW1lIjoiVW5rbm93bi5wZGYiLCJjb250ZW50VHlwZSI6ImFwcGxpY2F0aW9uL3BkZiIsImlhdCI6MTcyODQ4NTg4MywiZXhwIjoxNzI4NTcyMjgzfQ.Xfy77XHSaNdKIMrf7GZzjnW_FPRI684XKGbNjPzyar4
                            publicDomainProof: null
                count: 4
